apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "version.configName" . }}
  labels:
    grafana_datasource: "1"
data:
  VERSION_POSTGRES_URL_HOST: "postgresql-pgpool.recipefy-database.svc.cluster.local"
  VERSION_POSTGRES_URL_PORT: "5432"
  VERSION_POSTGRES_DB_NAME: "version"
  VERSION_MONGO_URL_HOSTS: "mongodb-0.mongodb-headless.recipefy-database.svc.cluster.local:27017,mongodb-1.mongodb-headless.recipefy-database.svc.cluster.local:27017"
  VERSION_MONGO_REPLICA_SET: "rs0"
  VERSION_MONGO_DB_NAME: "recipefy"
