apiVersion: v1
kind: Secret
metadata:
    name: version-secret
type: Opaque
stringData:
    VERSION_POSTGRES_USER: ENC[AES256_GCM,data:/Luf7JU=,iv:jIrGDagK0Yr2BgmMvSPSFutz/USFn/1BMOSHkisHnvo=,tag:bKJRI3ns4wEIYeomRY/+OA==,type:str]
    VERSION_POSTGRES_PASSWORD: ENC[AES256_GCM,data:+JQl4GA8OUk=,iv:KWmHWnLONQXfIWfskFAOxJ5dwQ7uFfgruXHBWVmzytM=,tag:W18U2rNBiXsCTe9m6abeyw==,type:str]
    VERSION_MONGO_USER: ENC[AES256_GCM,data:iFuNQg==,iv:G4Hjfe8bOcnSGzWdWcWaqjWJY089zrgDCzNrbDuT4Ec=,tag:6nfsBN3zkx3W+8mZ5AZZig==,type:str]
    VERSION_MONGO_PASSWORD: ENC[AES256_GCM,data:FGcFMgbaXg64y/QlfN9l+A==,iv:2x3D5ShiX0MtfbrXKxiS/bJJJQrR8jlxVbVQTEeXwNo=,tag:DnJEI6oCqEeEVcw1FiKggQ==,type:str]
sops:
    age:
        - recipient: age120tm04f69wuvcnrssp6a5ysc6hm544cdsw7rspcjn6m9976tcavs0ftw20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUDNXdUZVNU9FbDNDWkVB
            VmNRUnI0Q3FzNUowb3FWTXdmK0Z3b1RZYkFvClhwQVNYaklCcXgrdkovdEFtUXo5
            ZVpDdlZyaXY4SHlNRG5xenUrRHRhYjQKLS0tIG5yUVFlTnQ2Vm9RRmRZQVJxY2s3
            amtuQjkva2MxMVRpQTJtRkNPNDR0amcK9FzCzcPQ0MGnL7i3adyGZw7KdZ5/+HVE
            dKWmOnzQQIbytS6O1ONMnWSjTAhP9LrcqF9dtbwCNm7vttL2wUiZqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T17:08:14Z"
    mac: ENC[AES256_GCM,data:hhayysqnKkNBP+/+9QI2UIQXpWcK1ahRVnTn7cD9NLDteyxtKvP3Q+Upcoe0FzVMDMzeiOqd/BRUFmzngKRiGh/xsrILiOBxDYJA6S5BdxGR3RYbL2RbhYgTLoUQpIQPb7rVo3ea7L7VfQk+FMdpCwrCTzCCfSvOlBkifd8QdaU=,iv:/x7NLib11ppaW2OcLkJOYVVZZQtsxNCqefV4fcBZtug=,tag:ZNckBxZTXRbZb0KNPELDfQ==,type:str]
    encrypted_regex: ^(data|stringData|.*_secret)$
    version: 3.10.2
