{
 "title": "Recipefy GenAI Microservice Monitoring",
 "tags": [
  "fast api",
  "docker"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"genai\", handler!~\"/(health|metrics)\"}[1m]) * 60) by (handler)",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"genai\", handler!~\"/(health|metrics)\"}[1m]) * 60) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Duration (P95)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"genai\", handler!~\"/(health|metrics)\"}[1m])) by (le, handler))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request Duration (P99)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"genai\", handler!~\"/(health|metrics)\"}[1m])) by (le, handler))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"genai\"}) by (instance) / 1024 / 1024",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"genai\"}[1m])",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}