{
 "title": "Recipefy Keycloak Microservice Monitoring",
 "tags": [
  "spring boot",
  "docker"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"keycloak-service\", uri!~\"/actuator/.*\"}[1m]) * 60) by (uri)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"keycloak-service\", uri!~\"/actuator/.*\"}[1m]) * 60) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request Duration (P95)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"keycloak-service\", uri!~\".*/(actuator|metrics).*\"}[1m])) by (le, uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request Duration (P99)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{job=\"keycloak-service\", uri!~\".*/(actuator|metrics).*\"}[1m])) by (le, uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"keycloak-service\"}) by (instance) / 1024 / 1024",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "CPU Usage (per pod)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"keycloak-service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}