namespace: recipefy-monitoring

name: alertmanager

image:
  repository: prom/alertmanager
  tag: v0.25.0
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 9093

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 512Mi

persistence:
  enabled: true
  storageClass: csi-rbd-sc
  size: 2Gi

livenessProbe:
  httpGet:
    path: /-/healthy
    port: 9093
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /-/ready
    port: 9093
  initialDelaySeconds: 5
  periodSeconds: 10

terminationGracePeriodSeconds: 60

serviceAccount:
  create: true
  automount: true

nodeSelector: {}
tolerations: []
