apiVersion: v1
kind: Secret
metadata:
    name: genai-secret
type: Opaque
stringData:
    OPEN_WEBUI_API_KEY: ENC[AES256_GCM,data:iG6qazFH+PV1mCZIPgK46yHy7r23AzmXnI4D0DCFNHQo9SI=,iv:SCRF2AehybOK2CzVkfHiXVbbi0fbYTik6DGRF3BbNsI=,tag:RqXjKteOaCCULXjBE1lC7g==,type:str]
sops:
    age:
        - recipient: age120tm04f69wuvcnrssp6a5ysc6hm544cdsw7rspcjn6m9976tcavs0ftw20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMklsUW1MdnVJOG9MSmdr
            ZTJRS05pQkZHZExQYTlXZkhMRE0yQkxrNVNVCm5FYmZhUWdudEMvSmhjbVFDZ0pB
            UnYyS1pyeFBrQ2NwOXZteFNQQml5Q1UKLS0tIGs3eksxcnZrd3ZvMjZwMC9PK2xZ
            cjhxTHVPYjRGa08wQ1Bjb2JtQnZPVzAKzBnQHy+sUQFFcziWIvjcCqnO/dDDOsmZ
            ha1Tr4YLnRqLE7qqZTRd/0aY9Dtw1WSgXP3YZ3ckRNvvLqTBNcpsDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T19:09:44Z"
    mac: ENC[AES256_GCM,data:abuTrCSUHuNwEyQl0urERwc3varvFYZ1NIdhYjY/D1Z4JYNraoKR/ULaxIgKBhOSYG2bS4l5j8rHqln08HgoDgx9LeYDJHJr/5UQF7nFp+MQWEYB22QWCYV7YAPWum7vwCOC3WDDRH0K9Q71ISSAuYzSQ/1Wy4Z2DQ0mqp28cHI=,iv:5zgpYg0inDKc8bwJ1/eP7odMPC4tS4HINQYHd9XqJ0M=,tag:aWwez/L4SPWiYtdugCRmAA==,type:str]
    encrypted_regex: ^(data|stringData|.*_secret)$
    version: 3.10.2
