{{- if and .Values.certificate.enabled .Values.ingress.enabled .Values.ingress.tls }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "grafana.certificateName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificate
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    helm.sh/chart: {{ include "grafana.chart" . }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
spec:
  secretName: {{ .Values.ingress.existingSecret }}
  issuerRef:
    kind: {{ include "grafana.certificateIssuerKind" . }}
    name: {{ include "grafana.certificateIssuerName" . }}
  commonName: {{ include "grafana.certificateCommonName" . }}
  dnsNames:
{{ include "grafana.certificateDnsNames" . | nindent 4 }}
  {{- with .Values.certificate.usages }}
  usages:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
