apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.configName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-headless:9090
        isDefault: true
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.team-breaking-build.svc.cluster.local:3100
