apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: '{{ .Values.namespace }}'
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:gt9PGu0=,iv:1AHV2hU4S4xjUIZVvZKa9gSMVPKpuQUpHOnP+zVvY2I=,tag:+Vxy0awWRJqEktferAqfnw==,type:str]
    admin-password: ENC[AES256_GCM,data:z1UvjXsSpEghlqYsP2YsXg==,iv:ViFAVYnPSxFuQizZOKgqBlHE1t4KxVLth4OQ7gP/9wo=,tag:fGnEis7zZpgiF7U6uWRZSg==,type:str]
sops:
    age:
        - recipient: age120tm04f69wuvcnrssp6a5ysc6hm544cdsw7rspcjn6m9976tcavs0ftw20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQVphcEJnOG9BckFLcEUz
            dWJFN0ZEekxVbnhjTjM3VzdjZlI1aHpBNmdRCmJpK2JScks2ZHdKVGl5NVMyVVVX
            c0ZpamRtOTNiTEpkKzYrM1FRL2J0bkEKLS0tIGFVQkloL29Ub0toTXF3aktWQS9W
            dFF3VTl2NUk3SnY2VjVJaXIyeHZxbmcKJ+WYiy0m/knjqM7OBnpZjToFweAuvbX9
            Rcbgh1AYNtLjCMcicIgK9rqPAoF0zG3i5ujBFk4N1FMaEBBeMa25Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T16:15:57Z"
    mac: ENC[AES256_GCM,data:1eZ8VKKB1Ux5CFEwcTq47Oju3zlde1Kp/kDcnH1YMGpUvWxZeX7PlMUDhtLY0Cxw50vv9L/Wx52lR6dMhXQ48Bi9FUpWzFkHfRbqCIE4TmI/CyLfyF9YEfRR/gJTPmyTn9sBcSVkmS+jRq7EMNihLmlxsxPMe6yJ/j7rz7aAXo8=,iv:SHCPfUQf25ArjueCPQLgwR8KONl6bFJx23Iww3PwHvQ=,tag:x2B9cWWQAlTt3GnALphY9g==,type:str]
    encrypted_regex: ^(data|stringData|.*_secret)$
    version: 3.10.2
