namespace: team-breaking-build-monitoring

name: grafana

image:
  repository: grafana/grafana
  tag: 10.0.3
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - hosts:
        - team-breaking-build.student.k8s.aet.cit.tum.de
      secretName: team-breaking-build-tls
  className: nginx
  hosts:
    - host: grafana.team-breaking-build.student.k8s.aet.cit.tum.de
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 200m

persistence:
  enabled: true
  storageClass: csi-rbd-sc
  size: 10Gi

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10

terminationGracePeriodSeconds: 60

serviceAccount:
  create: true
  automount: true

nodeSelector: {}
tolerations: []
