serviceMonitor:
  enabled: true

rbac:
  create: false

extraObjects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: alloy
      namespace: recipefy
    rules:
      - apiGroups: [""]
        resources: ["pods", "services", "endpoints", "namespaces"]
        verbs: ["get", "list", "watch"]
      - apiGroups: [""]
        resources: ["pods/log"]
        verbs: ["get", "list", "watch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: alloy
      namespace: recipefy
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: alloy
    subjects:
      - kind: ServiceAccount
        name: alloy
        namespace: recipefy

alloy:
  mounts:
    varlog: true
  configMap:
    create: true
    name: alloy-settings
    content: |
      logging {
        level  = "info"
        format = "logfmt"
      }
        
      discovery.kubernetes "pods_ns" {
        role       = "pod"
        namespaces {
          names = ["recipefy"]
        }
      }
      
      loki.source.kubernetes "pods" {
        targets    = discovery.kubernetes.pods_ns.targets
        forward_to = [loki.write.local.receiver]
      }
      
      loki.write "local" {
        endpoint {
          url = "http://loki.recipefy-monitoring.svc.cluster.local:3100/loki/api/v1/push"
        }
      }
