apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:/2+ys7bsyfwJoTzfJBgOnw==,iv:4CvXEhQcXiv8/6TBMBh+WqpVcku+tI5hLbAg5uVo6EU=,tag:ops/YGVLLIy3hBlCN9ZJeQ==,type:str]
    mongodb-replica-set-key: ENC[AES256_GCM,data:rsRbsSf/Oot5nw==,iv:g0CpVwWRwnCQZ1QbIstmod0On+9EHOwcmgSFvZgXfvM=,tag:KukQfRDRx52duyp44HyEpw==,type:str]
    mongodb-root-user: ENC[AES256_GCM,data:N6FjT/I=,iv:fmQxN6xFrOyeuIu+Hb9DYagNGqmGHjEDUuRWXqXV+7k=,tag:Z01WAIkJ6uqsKxbalNzwkw==,type:str]
sops:
    age:
        - recipient: age120tm04f69wuvcnrssp6a5ysc6hm544cdsw7rspcjn6m9976tcavs0ftw20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5U0oyVnIxdi9FWmJmdS9S
            RHdZcjRNeWdtMEgyNG03K0MzdmZHRjJlSmhBCitKVzZOMmpab3NXVWN4YWE4aHlX
            aVJFR1BWZVhRdnhTNDFBU0FtSDVOVG8KLS0tIGN1bTE2WE9HdVdUTjJRaXV3VVd6
            UG9WaWlBUm5VNlRVV1hRbUluTkVjK1EKnJ4DlGkxa5a0mTJmJYCxTfB5r22XpOsU
            aLLoJsY/ZvIfcfVvPv6EjfBCJkiaReUD1xrFOIR/c1icbnnVymQ1cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T15:51:23Z"
    mac: ENC[AES256_GCM,data:voQ91j77QzyNgUZV3FVxXe1dV6lY2hEob7QMeLYUrq5CCx41stJXHCBj+uJ6Pv9WHC/QyxLARpIlkfA2l1ba7xMfuT8M2iznfY5XgVEb/AIkBjmUSf/EL6lN6l2Q/ZuAD6nR6Ht11bMHvqxuXtMboTz0s4UDUARNgwF94Yh02J4=,iv:ZDUgkvmSR20R7yjl8GmuWs+IRjtJui3YzN4OuBOTeJk=,tag:vBjlXrYcsTYnhpsB5FRDYg==,type:str]
    encrypted_regex: ^(data|stringData|.*_secret)$
    version: 3.10.2
