apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weaviate.configName" . }}
  labels:
    grafana_datasource: "1"
data:
  TRANSFORMERS_INFERENCE_API: "http://transformers.recipefy.svc.cluster.local:8080"
