apiVersion: v1
kind: Service
metadata:
  name: {{ include "weaviate.fullname" . }}
  labels:
    {{- include "weaviate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
      - port: {{ .Values.service.port }}
        targetPort: {{ .Values.container.portName }}
        protocol: {{ .Values.container.protocol }}
        name: {{ .Values.container.portName }}
      - port: {{ .Values.service.grpcPort }}
        targetPort: grpc
        protocol: TCP
        name: grpc
  selector: 
    {{- include "weaviate.selectorLabels" . | nindent 4 }}
