services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    env_file:
     - ./.env
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: keycloak
    env_file:
     - ./.env
    depends_on:
      - postgres
    restart: always
    environment:
      KC_DB:                         ${KC_DB}
      KC_DB_URL_HOST:                postgres
      KC_DB_URL_PORT:                5432
      KC_DB_DATABASE:                ${KC_DB_DATABASE}
      KC_DB_USERNAME:                ${KC_DB_USERNAME}
      KC_DB_PASSWORD:                ${KC_DB_PASSWORD}
      KC_DB_SCHEMA:                  ${KC_DB_SCHEMA}

      KC_BOOTSTRAP_ADMIN_USERNAME:   ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD:   ${KC_BOOTSTRAP_ADMIN_PASSWORD}

      KC_HOSTNAME:                   keycloak
      KC_PROXY:                      edge
      KC_LOG_LEVEL:                  info
      KC_METRICS_ENABLED:            true
      KC_HEALTH_ENABLED:             true
      KC_HTTP_ENABLED:               true
    command: start
    ports:
      - "8081:8080"
      - "8443:8443"
    volumes:
      - ./keycloak_data:/opt/keycloak/data

  gateway:
    build:
      context: ./api-gateway
    image: api-gateway:latest
    env_file:
     - ./.env
    restart: always
    container_name: api-gateway
    depends_on:
      - keycloak
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: users
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://localhost:8082
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/users

      APP_SECURITY_CORS_ALLOWED_ORIGINS_0: localhost
      APP_SECURITY_CORS_ALLOWED_ORIGINS_1: nebeklion.com

      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALMS: recipefy

