apiVersion: v1
kind: Secret
metadata:
    name: postgresql-secret
    namespace: recipefy-database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:/ly5050=,iv:xBQRLmx0cyD+uwZW6GxfAn7zUEWmfR9AX559fXAnvb8=,tag:l77fDWUJTr1GJYQiR6ImCQ==,type:str]
    #ENC[AES256_GCM,data:9LYaW3wpUb5GPrH8Hr4F/68YAaU=,iv:PaYvt7sircf5UFNsfGCcl6YyenQGb3gej1sSupbWzPo=,tag:izQNqMowUp7ogP5QOtTCdQ==,type:comment]
    password: ENC[AES256_GCM,data:bVJiwwTWM7AgEfMkZi2Sew==,iv:NhenneAfMMdSvkIdNQN5GwLnFWTooOkPeXssHj82t5I=,tag:4OydofX15URieWzO6tsJ7w==,type:str]
    #ENC[AES256_GCM,data:4WzS5UPDqR+My+To2quDrsPUHN5x7cmop8pQXA==,iv:tntVGnqnWcCixJq16RwbSCpdLXqeC2xDt2fyDzpMx88=,tag:U6roo0fyLLmTkOsxAUdnyA==,type:comment]
    postgres-password: ENC[AES256_GCM,data:Bqd61LQXTvpSHXyApBWrLA==,iv:mDDVoEqKHru2aIRPeMCzWLU6yEgiI/cs1Z0IjFVfGqo=,tag:9HgxIo6Jhvs7Qjg3CT9hTQ==,type:str]
    #ENC[AES256_GCM,data:TvlBIzAp+VimdRZ+Y/jg2uEJoW0IEN7XMgFVOIpLEN86Ye/a6Q==,iv:jLfX1V2Bmtfh9F8gLxsZj00f/shpzfn4a/GYtPUs9HQ=,tag:RPgsftaO5lswmBzpkYGZOA==,type:comment]
    repmgr-password: ENC[AES256_GCM,data:fGkOMRKvspu83Q==,iv:eFWHe5dZdr/MCR8z++ZNK8eQtai3JtfSpyo1TIeZ2PU=,tag:C39mQwkZ+z9jM/GxiQD6FA==,type:str]
sops:
    age:
        - recipient: age120tm04f69wuvcnrssp6a5ysc6hm544cdsw7rspcjn6m9976tcavs0ftw20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUkxIRUQyaUFCZU9xc0FQ
            K2lVK25CSlVJaW0wT1FNVFovU1VscVNCeVdVCjVGVnRkUytMck5SWDlsQVYxekxV
            L1lhWGFJQVdQak5VUVY0K09BS1RLajAKLS0tIEtMY0E4U0hreVJONk9Fem9zaXVq
            MW8vMlE2WmpjWGVMNWdzVEtzY3hHb0UKtboeU6ubEs2vGf20jdJ6UiW2uOfU1Lme
            8nvaHdx5/C00RcFbklfFGUDqcgUCQCt0GNCBt3LinK9wV6VVK24c1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T18:28:21Z"
    mac: ENC[AES256_GCM,data:grJV83AAUfoby4l/iDLBrsg53a06ZNQNHF7OiW5FwysBjcD1FD0oyzHgOjzr9nG/pJbP1BFR3BYxdCW4vLVM2QkKfd3S1tj7uakndSCj1In/29xV4s7PKP/MJfipIz2rOUkH5TrkuZykwNvQjkI8iBGh2rxoGTS2RioHCSNk4NU=,iv:LCFMIcuJsJekeGEpDkGclDHPA8URsyxMsSeSW169jWE=,tag:nEF6SGzx+Bu0fpLjrXcMUg==,type:str]
    encrypted_regex: ^(data|stringData|.*_secret)$
    version: 3.10.2
