spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: recipe
          uri: http://localhost:8081
          predicates:
            - Path=/recipe
        - id: version
          uri: http://localhost:8082
          predicates:
            - Path=/version

logging:
  level:
    root: INFO
    com.recipefy.gateway: DEBUG
    com.recipefy.gateway.config: DEBUG
    com.recipefy.gateway.controller: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

app:
  security:
    cors:
      allowed-origins:
        - localhost

keycloak:
  base-url: http://localhost:8085
  realms: recipfy
  introspect-url: ${keycloak.base-url}/realms/${keycloak.realms}/protocol/openid-connect/token/introspect
  client-id: ${KEYCLOAK_CREDENTIALS_RECIPEFY_CLIENT_ID}
  client-secret: ${KEYCLOAK_CREDENTIALS_RECIPEFY_CLIENT_SECRET}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
