spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
        - id: recipe
          uri: http://localhost:8081
          predicates:
            - Path=/recipe
        - id: version
          uri: http://localhost:8082
          predicates:
            - Path=/version
app:
  security:
    cors:
      allowed-origins:
        - localhost

keycloak:
  base-url: http://localhost:8085
  realms: recipfy
  introspect-url: ${keycloak.base-url}/realms/${keycloak.realms}/protocol/openid-connect/token/introspect
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
