fullnameOverride: "postgres"

cluster:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-7
  instances: 2
  storage:
    size: 50Gi
  walStorage:
    size: 10Gi
  affinity:
    topologyKey: topology.csi.vmware.com/host
  monitoring:
    enabled: true
  postgresql:
    parameters:
      max_connections: "100"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      pg_stat_statements.track: all
  resources:
    requests:
      memory: 1Gi
      cpu: 500m

poolers:
  - name: rw
    type: rw
    poolMode: transaction
    instances: 3
    parameters:
      max_client_conn: "5000"
      default_pool_size: "70"
      min_pool_size: "10"
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
    template:
      spec:
        containers:
          - name: pgbouncer
            resources:
              requests:
                cpu: 100m
                memory: 500Mi
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: topology.csi.vmware.com/host
                      operator: Exists

