global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'recipe-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['recipe:8080']

  - job_name: 'version-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['version:8080']

  - job_name: 'genai'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['genai:8080']

  - job_name: 'keycloak-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['keycloak-service:8080']
