replicaCount: 1

image:
  repository: ghcr.io/aet-devops25/team-breaking-build/server/api-gateway
  tag: latest
  pullPolicy: Always

serviceAccount:
  create: true
  automount: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  prometheus.io/port: "8080"
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  app.kubernetes.io/version: "1.0.0"
  sidecar.istio.io/inject: "true"

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 5

envFrom:
  - configMapRef:
      name: recipefy-gateway-config
  - secretRef:
      name: recipefy-gateway-secret
