{
 "title": "Gateway Service Dashboard",
 "tags": [ "gateway" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"recipe-service\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"recipe-service\"})*100/sum(jvm_memory_max_bytes{job=\"recipe-service\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"recipe-service\"})*100/sum(jvm_memory_max_bytes{job=\"recipe-service\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{job=\"recipe-service\"}",
     "legendFormat": "Open Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"recipe-service\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"recipe-service\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{job=\"recipe-service\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{job=\"recipe-service\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{job=\"recipe-service\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{job=\"gateway-service\"})"
    }
   ]
  },
  {
   "title": "Total Successful Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", job=\"gateway-service\", uri!~\"/actuator.*\"})"
    }
   ]
  },
  {
   "title": "Total Unsuccessful Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", job=\"gateway-service\"})"
    }
   ]
  },
  {
   "title": "Total Unsuccessful Requests By routeId",
   "type": "graph",
   "description": "Total Unsuccessful Requests By routeId",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", job=\"gateway-service\"}[1m])) by (routeId, httpStatusCode, outcome, status)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Total QPS",
   "type": "graph",
   "description": "Total QPS for spring cloud gateway requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{job=\"gateway-service\"}[5m]))",
     "legendFormat": "total qps"
    },
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{job=\"gateway-service\",status=\"OK\"}[5m]))",
     "legendFormat": "total ok qps"
    }
   ]
  },
  {
   "title": "QPS by service",
   "type": "graph",
   "description": "QPS for spring cloud gateway requests by service",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spring_cloud_gateway_requests_seconds_count{job=\"gateway-service\"}[5m])) by (routeId)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Latency for spring cloud gateway requests",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(spring_cloud_gateway_requests_seconds_sum{job=\"gateway-service\"}[30s])) by (routeId)) / \n(sum(rate(spring_cloud_gateway_requests_seconds_count{job=\"gateway-service\"}[30s])) by (routeId)) * 1000",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$routeId",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_sum{job=\"gateway-service\"}) by (routeId) / sum(spring_cloud_gateway_requests_seconds_count{job=\"gateway-service\"}) by (routeId)",
     "legendFormat": "{{ routeId }}"
    }
   ]
  },
  {
   "title": "Successful API Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$routeId Success API Gateway Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 59 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", job=\"gateway-service\"}",
     "legendFormat": "{{ routeId }}"
    }
   ]
  },
  {
   "title": "Unsuccessful API Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$routeId Unsuccessful GW Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 67 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", job=\"gateway-service\"}",
     "legendFormat": "{{ routeId }}"
    }
   ]
  },
  {
   "title": "API / HTTP Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$routeId",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 75 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{job=\"gateway-service\"}) by (routeId, status)",
     "legendFormat": "{{ routeId / status }}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Minor GC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(jvm_gc_pause_seconds_count{action=\"end of minor GC\"}[5m])) * 300",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Major GC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[5m])) * 300",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total/jvm_gc_memory_allocated_bytes_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}