apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prometheus.roleName" . }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - endpoints
      - services
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "prometheus.roleBindingName" . }}
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "prometheus.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
