apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}-headless
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ include "prometheus.name" . }}
  ports:
    - port: 9090
      name: web
