apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "prometheus.name" . }}
  serviceName: {{ include "prometheus.fullname" . }}-headless
  template:
    metadata:
      labels:
        app: {{ include "prometheus.name" . }}
    spec:
      serviceAccountName: {{ include "prometheus.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: prometheus
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--config.file=/opt/bitnami/prometheus/conf/prometheus.yml"
            - "--storage.tsdb.path=/opt/bitnami/prometheus/data"
            - "--web.console.libraries=/opt/bitnami/prometheus/console_libraries"
            - "--web.console.templates=/opt/bitnami/prometheus/consoles"
            - "--storage.tsdb.retention.time=15d"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /opt/bitnami/prometheus/conf
            - name: data
              mountPath: /opt/bitnami/prometheus/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            capabilities:
              drop:
              {{- range .Values.securityContext.capabilities.drop }}
                - {{ . }}
              {{- end }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "prometheus.configName" . }}
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          {{- toYaml .Values.persistence.annotations | nindent 10 }}
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
