apiVersion: v1
kind: Secret
metadata:
    name: recipe-secret
    namespace: '{{ .Values.namespace }}'
type: Opaque
stringData:
    RECIPE_POSTGRES_USER: ENC[AES256_GCM,data:BL8vKM0=,iv:WVOymOwnFSxQZZcPjZzjodkL3UNtHXNWWLEn/wQeS7k=,tag:4ijlrLWRbi1lvztQLqDODA==,type:str]
    RECIPE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:nh7Xup1MdLg=,iv:NEKqX+YbhsQXiOUaqoRwLrtUlNT0tD7bwvhCaWHLQHA=,tag:JkXAqIZrtukvTk8yU9mC2Q==,type:str]
    RECIPE_POSTGRES_DB_NAME: ENC[AES256_GCM,data:gBMN3iFQ,iv:yCLfiQR/zIslkSMYpk+JED2RwP8YEB3MovRsdBkItpc=,tag:qkoWKKHNse4JVSh/FcT/kg==,type:str]
sops:
    age:
        - recipient: age120tm04f69wuvcnrssp6a5ysc6hm544cdsw7rspcjn6m9976tcavs0ftw20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa1VtNWYzK0dTb3F5VzZ1
            ZXVTZGpDZWlvcHpoY1lyQUIxSUM2a0VLTWw4Ck1XUnluSEtRN28zNzA0V1VDMDF5
            RlhsQkxPRGxSeTdSamtwR2xEbzNHVGMKLS0tIHFnaEk1bzVUVmpGM1dpWWZtTEZN
            VmhYS0xhN0JEdCtkUGVGNXVNdm1CM0UKsT0rwWQRDQQ8FaeJhAUu3YdzSxlWRviZ
            i/Dh/Yf6WioWYGM5NPGREkBkvma2QhVa7IiLIrcXbWtjt+s28PBjeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T19:30:38Z"
    mac: ENC[AES256_GCM,data:2EnNMQBolRawFAQOI9LdV9IbxD2ZwiuOv+l0vtqTNXy/L6EbQoWGHsAQzyyz4fdxgWprola1CqkJ3wye4Lz8bXMV5n3ZfMCOLIb95jcH0GzCqayVESHx7avjBJgxP00FXf8oSYiXF7M/ysORg6GaIFNJEz7OzurjvMyzacvDHTA=,iv:cAKajLIffgW8G6KyysL2lzkzu4+ubh0ZGEFYp00Oxa0=,tag:kVjCXxpjBF0KB/fIdQqmSg==,type:str]
    encrypted_regex: ^(data|stringData|.*_secret)$
    version: 3.10.2
