loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2025-06-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    max_chunk_age: 3h
    chunk_encoding: snappy
  limits_config:
    ingestion_rate_mb: 8
    ingestion_burst_size_mb: 32
  tracing:
    enabled: true
  querier:
    max_concurrent: 4

sidecar:
  rules:
    enabled: false

rbac:
  namespaced: true

gateway:
  enabled: false

deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      cpu: 250m
      memory: 2Gi
  extraEnv:
    - name: GOMEMLIMIT
      value: 3750MiB

chunksCache:
  writebackSizeLimit: 10MB

minio:
  enabled: true

lokiCanary:
  enabled: false

test:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0

extraObjects:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: loki-role
      namespace: team-breaking-build
    rules:
      - apiGroups: [""]
        resources: ["configmaps", "secrets"]
        verbs: ["get", "list", "watch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: loki-role
      namespace: team-breaking-build
    subjects:
      - kind: ServiceAccount
        name: loki
        namespace: team-breaking-build
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: loki-role
