apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-alertmanager.configName" . }}
  namespace: {{ .Values.namespace }}
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'default'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
      - name: 'default'
        email_configs:
          - to: 'iremecemyelkanat@gmail.com'
            from: 'apprecipefy@gmail.com'
            smarthost: 'smtp.gmail.com:587'
            auth_username: 'apprecipefy@gmail.com'
            auth_identity: 'apprecipefy@gmail.com'
            auth_password_file: /etc/alertmanager/secrets/smtp_password
            require_tls: true
