apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "prometheus-alertmanager.pvcName" . }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
