apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-alertmanager.fullname" . }}
  labels:
    {{- include "prometheus-alertmanager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    app: {{ include "prometheus-alertmanager.name" . }}
