name: CI/CD Pipeline for API-Gateway

on:
  push:
    paths:
      - ".github/workflows/api-gateway-ci-cd.yml"
      - 'server/api-gateway/**'
      - 'helm/api-gateway/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: server/api-gateway
  WORKING_DIRECTORY: server/api-gateway
  NAMESPACE: recipefy
  RELEASE_NAME: api-gateway
  CHART_PATH: ./helm/api-gateway

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Gradle Build
        run: ./gradlew build --no-daemon

  build:
    name: Build and Push Docker Images
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.WORKING_DIRECTORY }}
          file: ./${{ env.WORKING_DIRECTORY }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  deploy:
    name: Deploy to Rancher with Helm
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Configure Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Set image tag
        run: |
          if [ -z "$GITHUB_SHA" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=sha-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          fi

      - name: Record deployment timestamp
        run: echo "DEPLOYMENT_TIMESTAMP=$(($(date +%s) * 1000))" >> $GITHUB_ENV

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install ${{ env.RELEASE_NAME }} ${{ env.CHART_PATH }} \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --namespace ${{ env.NAMESPACE }} \
            --wait --timeout 5m

      - name: Annotate Grafana with deployment
        env:
          GRAFANA_URL: https://grafana.team-breaking-build.student.k8s.aet.cit.tum.de
          GRAFANA_DASHBOARD_UID: gateway-service
          GRAFANA_SERVICE_TOKEN: ${{ secrets.GRAFANA_SERVICE_TOKEN }}
          DEPLOYMENT_TIMESTAMP: ${{ env.DEPLOYMENT_TIMESTAMP }}
        run: |
          curl -X POST "$GRAFANA_URL/api/annotations" \
            -H "Authorization: Bearer $GRAFANA_SERVICE_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"dashboardUID\": \"$GRAFANA_DASHBOARD_UID\",
              \"time\": $DEPLOYMENT_TIMESTAMP,
              \"tags\": [\"deployment\"],
              \"text\": \"🚀 Deployed gateway-service\"
            }"
