name: Deploy API Documentation

on:
  push:
    branches:
      - main
      - feature/api-docs
    paths:
      - 'api/openapi.yaml'
      - '.github/workflows/deploy-api-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4



      - name: Create API documentation site
        run: |
          # Create docs directory
          mkdir -p docs
          
          # Create index.html with Swagger UI
          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Recipefy API Documentation</title>
              <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui.css" />
              <style>
                  html {
                      box-sizing: border-box;
                      overflow: -moz-scrollbars-vertical;
                      overflow-y: scroll;
                  }
                  *, *:before, *:after {
                      box-sizing: inherit;
                  }
                  body {
                      margin:0;
                      background: #fafafa;
                  }
                  .swagger-ui .topbar {
                      background-color: #2c3e50;
                      padding: 10px 0;
                  }
                  .swagger-ui .topbar .download-url-wrapper .select-label {
                      color: #fff;
                  }
                  .swagger-ui .info .title {
                      color: #2c3e50;
                      font-size: 36px;
                      font-weight: 600;
                  }
                  .swagger-ui .info .description {
                      font-size: 16px;
                      line-height: 1.6;
                  }
                  .swagger-ui .scheme-container {
                      background: #f8f9fa;
                      border-radius: 4px;
                      padding: 20px;
                      margin: 20px 0;
                  }
              </style>
          </head>
          <body>
              <div id="swagger-ui"></div>
              <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"></script>
              <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js"></script>
              <script>
                  window.onload = function() {
                      const ui = SwaggerUIBundle({
                          url: './openapi.yaml',
                          dom_id: '#swagger-ui',
                          deepLinking: true,
                          presets: [
                              SwaggerUIBundle.presets.apis,
                              SwaggerUIStandalonePreset
                          ],
                          plugins: [
                              SwaggerUIBundle.plugins.DownloadUrl
                          ],
                          layout: "StandaloneLayout",
                          validatorUrl: null,
                          docExpansion: "list",
                          filter: true,
                          showExtensions: true,
                          showCommonExtensions: true,
                          tryItOutEnabled: true,
                          requestInterceptor: function(request) {
                              // Add CORS headers for testing
                              request.headers['Access-Control-Allow-Origin'] = '*';
                              return request;
                          },
                          onComplete: function() {
                              console.log('Swagger UI loaded successfully');
                          }
                      });
                  };
              </script>
          </body>
          </html>
          EOF
          
          # Copy the OpenAPI specification
          cp api/openapi.yaml docs/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
