name: Deploy MongoDB

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      NAMESPACE: recipefy-database
      RELEASE_NAME: mongodb
      CHART_NAME: bitnami/mongodb
      VALUES_FILE: ./helm/mongodb/values.yaml
      SECRET_FILE_ENCRYPTED: ./helm/mongodb/secret.yaml
      SECRET_FILE_DECRYPTED: ./helm/mongodb/secret.decrypted.yaml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SOPS
        uses: nhedger/setup-sops@v2
        with:
          version: 3.8.1

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Configure Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ env.KUBE_CONFIG }}

      - name: Decrypt secret
        run: |
          sops --decrypt "$SECRET_FILE_ENCRYPTED" > "$SECRET_FILE_DECRYPTED"

      - name: Apply secret to Kubernetes
        run: |
          kubectl apply -f "$SECRET_FILE_DECRYPTED" --namespace "$NAMESPACE"

      - name: Deploy MongoDB with Helm
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm upgrade --install "$RELEASE_NAME" "$CHART_NAME" \
            -f "$VALUES_FILE" \
            --namespace "$NAMESPACE" \
            --create-namespace

      - name: Clean up decrypted file
        run: rm -f "$SECRET_FILE_DECRYPTED"
