name: Deploy PostgreSQL

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      NAMESPACE: recipefy-database
      RELEASE_NAME: postgresql
      CHART_NAME: bitnami/postgresql-ha
      VALUES_FILE: ./helm/postgresql/values.yaml
      CONFIG_FILE: ./helm/postgresql/configmap.yaml
      POSTGRESQL_SECRET_FILE_ENCRYPTED: ./helm/postgresql/postgresql-secret.yaml
      POSTGRESQL_SECRET_FILE_DECRYPTED: ./helm/postgresql/postgresql-secret.decrypted.yaml
      PGPOOL_SECRET_FILE_ENCRYPTED: ./helm/postgresql/pgpool-secret.yaml
      PGPOOL_SECRET_FILE_DECRYPTED: ./helm/postgresql/pgpool-secret.decrypted.yaml

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SOPS
        uses: nhedger/setup-sops@v2
        with:
          version: 3.8.1

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Configure Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ env.KUBE_CONFIG }}

      - name: Decrypt postgresql secret
        run: |
          sops --decrypt "$POSTGRESQL_SECRET_FILE_ENCRYPTED" > "$POSTGRESQL_SECRET_FILE_DECRYPTED" && \
          sops --decrypt "$PGPOOL_SECRET_FILE_ENCRYPTED" > "$PGPOOL_SECRET_FILE_DECRYPTED"

      - name: Apply secret and config to Kubernetes
        run: |
          kubectl apply -f "$POSTGRESQL_SECRET_FILE_DECRYPTED" --namespace "$NAMESPACE" && \
          kubectl apply -f "$PGPOOL_SECRET_FILE_DECRYPTED" --namespace "$NAMESPACE" && \
          kubectl apply -f "$CONFIG_FILE" --namespace "$NAMESPACE"

      - name: Deploy PostgreSQL with Helm
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm upgrade --install "$RELEASE_NAME" "$CHART_NAME" \
            -f "$VALUES_FILE" \
            --namespace "$NAMESPACE"

      - name: Clean up decrypted file
        run: rm -f "$POSTGRESQL_SECRET_FILE_ENCRYPTED" && rm -f "$PGPOOL_SECRET_FILE_DECRYPTED"
