name: CI/CD Pipeline for Transformers Inference Service

on:
  push:
    paths:
      - 'helm/transformers/**'
  workflow_dispatch:

env:
  HELM_NAMESPACE: team-breaking-build
  HELM_RELEASE_NAME: recipefy-transformers
  CHART_PATH: ./helm/transformers

jobs:
  validate:
    name: Validate Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Validate Helm Chart
        run: |
          helm lint ${{ env.CHART_PATH }}
          helm template ${{ env.HELM_RELEASE_NAME }} ${{ env.CHART_PATH }} \
            --namespace ${{ env.HELM_NAMESPACE }} > /dev/null

  deploy:
    name: Deploy to Rancher with Helm
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Configure Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ${{ env.CHART_PATH }} \
            --namespace ${{ env.HELM_NAMESPACE }} \
            --wait --timeout 5m
