name: CI/CD Pipeline for Weaviate Vector Database

on:
  push:
    paths:
      - 'helm/weaviate/**'
  workflow_dispatch:

env:
  HELM_NAMESPACE: team-breaking-build
  HELM_RELEASE_NAME: recipefy-weaviate
  CHART_PATH: ./helm/weaviate

jobs:
  validate:
    name: Validate Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Validate Helm Chart
        run: |
          helm lint ${{ env.CHART_PATH }}
          helm template ${{ env.HELM_RELEASE_NAME }} ${{ env.CHART_PATH }} \
            --namespace ${{ env.HELM_NAMESPACE }} > /dev/null

  deploy:
    name: Deploy to Rancher with Helm
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Configure Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ${{ env.CHART_PATH }} \
            --namespace ${{ env.HELM_NAMESPACE }} \
            --wait --timeout 5m

      - name: Verify Deployment
        run: |
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=weaviate \
            --namespace ${{ env.HELM_NAMESPACE }} --timeout=300s
          
          # Test weaviate readiness endpoint
          kubectl run test-weaviate --rm -i --restart=Never \
            --namespace ${{ env.HELM_NAMESPACE }} \
            --image=curlimages/curl:latest \
            -- curl -f http://${{ env.HELM_RELEASE_NAME }}:8080/v1/.well-known/ready 